<?php if(Mage::getStoreConfig('hauptrolle/facebook_comments/app_id')): ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo Mage::getStoreConfig('hauptrolle/facebook_comments/app_id')  ?>";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<div class="box-collateral box-facebookcomments">
    <h2><?php echo $this->__('Facebook Comments') ?></h2>
    <div class="fb-comments" data-href="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>" data-width="<?php echo Mage::getStoreConfig('hauptrolle/facebook_comments/app_width') ?>" data-num-posts="<?php echo Mage::getStoreConfig('hauptrolle/facebook_comments/app_max') ?>"></div>
</div>
<?php endif; ?>